import type { BlockConfig, Question } from "@/types/quiz";

export const BLOCKS: BlockConfig[] = [
  { id: 1, title: "Sobre você", subtitle: "Pra começar, queremos te conhecer" },
  {
    id: 2,
    title: "Seu momento de vida",
    subtitle: "Os sonhos só fazem sentido em contexto",
  },
  { id: 3, title: "" },
  { id: 4, title: "O sonho" },
  { id: 5, title: "Padrões" },
  {
    id: 6,
    title: "Sua pergunta",
    subtitle: "Quase lá. Essa é a parte mais importante.",
  },
];

export const QUESTIONS: Question[] = [
  // BLOCO 1 — Sobre você
  {
    id: "q1",
    block: 1,
    blockOrder: 1,
    field: "nome",
    type: "text",
    inputType: "text",
    text: "Como podemos te chamar?",
    placeholder: "Seu primeiro nome",
    minLength: 2,
    required: true,
  },
  {
    id: "q2",
    block: 1,
    blockOrder: 2,
    field: "idade",
    type: "single",
    text: "Qual a sua idade?",
    required: true,
    options: [
      { value: "18-24", label: "18-24" },
      { value: "25-30", label: "25-30" },
      { value: "31-35", label: "31-35" },
      { value: "36-40", label: "36-40" },
      { value: "41-45", label: "41-45" },
      { value: "46-55", label: "46-55" },
      { value: "55+", label: "55+" },
    ],
  },
  {
    id: "q3",
    block: 1,
    blockOrder: 3,
    field: "identificacao_espiritual",
    type: "single",
    text: "Como você se identifica espiritualmente hoje?",
    required: true,
    options: [
      {
        value: "crista_praticante",
        label: "Pratico minha fé cristã (evangélica, católica, etc.)",
      },
      {
        value: "crista_nao_praticante",
        label: "Acredito no cristianismo, mas não pratico",
      },
      {
        value: "espiritualizada",
        label: "Tenho espiritualidade sem religião definida",
      },
      { value: "em_busca", label: "Em busca / descobrindo" },
      { value: "cetica", label: "Sem religião / tenho visão cética" },
      {
        value: "outra",
        label: "Outra",
        extraField: {
          field: "identificacao_espiritual_outra",
          placeholder: "Conte um pouco...",
        },
      },
    ],
  },
  {
    id: "q4",
    block: 1,
    blockOrder: 4,
    field: "email",
    type: "text",
    inputType: "email",
    text: "Qual o seu e-mail?",
    subtext: "Em até alguns minutos sua análise chegará aqui",
    placeholder: "voce@exemplo.com",
    required: true,
  },

  // BLOCO 2 — Seu momento de vida
  {
    id: "q5",
    block: 2,
    blockOrder: 1,
    field: "areas_de_vida",
    type: "multi",
    text: "Em qual área da sua vida você tem prestado mais atenção agora?",
    subtext: "Escolha até 2",
    required: true,
    minSelections: 1,
    maxSelections: 2,
    options: [
      { value: "relacionamento", label: "Relacionamento amoroso" },
      { value: "familia", label: "Família e relações próximas" },
      { value: "carreira", label: "Carreira / trabalho" },
      { value: "dinheiro", label: "Dinheiro e estabilidade" },
      { value: "saude_fisica", label: "Saúde física" },
      { value: "saude_mental", label: "Saúde mental / emocional" },
      { value: "espiritualidade", label: "Espiritualidade / propósito" },
      { value: "parentalidade", label: "Parentalidade (atual ou futura)" },
      { value: "autoconhecimento", label: "Autoconhecimento geral" },
    ],
  },
  {
    id: "q6",
    block: 2,
    blockOrder: 2,
    field: "evento_recente",
    type: "single",
    text: "Aconteceu algo importante na sua vida nos últimos 90 dias?",
    required: true,
    options: [
      { value: "muito_significativo", label: "Sim, algo muito significativo" },
      { value: "mudancas_relevantes", label: "Sim, mudanças relevantes" },
      { value: "nada_especial", label: "Nada de muito especial" },
      { value: "periodo_dificil", label: "Foi um período difícil" },
      { value: "prefiro_nao_comentar", label: "Prefiro não comentar" },
    ],
  },
  {
    id: "q7",
    block: 2,
    blockOrder: 3,
    field: "contexto_pessoal",
    type: "textarea",
    text: "Se quiser, conte brevemente o que está acontecendo agora na sua vida.",
    placeholder:
      "Você não precisa entrar em muitos detalhes — só o que faz sentido pra você compartilhar.",
    maxLength: 1000,
    required: false,
  },
  {
    id: "q8",
    block: 2,
    blockOrder: 4,
    field: "estado_emocional",
    type: "single",
    text: "Como você descreveria seu estado emocional predominante nas últimas semanas?",
    required: true,
    options: [
      { value: "ansiosa", label: "Ansiedade / inquietação" },
      { value: "triste", label: "Tristeza / pra baixo" },
      { value: "confusa", label: "Confusão / sem direção" },
      { value: "em_transformacao", label: "Em transformação" },
      { value: "tranquila", label: "Tranquilidade / em paz" },
      { value: "empolgada", label: "Empolgação / esperança" },
      { value: "cansada", label: "Cansaço / esgotamento" },
    ],
  },

  // BLOCO 4 — O sonho (block 3 é só intro)
  {
    id: "q9",
    block: 4,
    blockOrder: 1,
    field: "quando_sonhou",
    type: "single",
    text: "Quando você teve esse sonho?",
    required: true,
    options: [
      { value: "esta_noite", label: "Esta noite / madrugada" },
      { value: "ultimos_3_dias", label: "Nos últimos 3 dias" },
      { value: "ultima_semana", label: "Na última semana" },
      { value: "ultimo_mes", label: "No último mês" },
      {
        value: "ha_mais_tempo",
        label: "Há mais tempo, mas ele ficou marcado",
      },
    ],
  },
  {
    id: "q10",
    block: 4,
    blockOrder: 2,
    field: "sonho_descricao",
    type: "textarea",
    text: "Descreva seu sonho com o máximo de detalhes possível.",
    subtext:
      "Conte como se estivesse narrando um filme. Quem aparecia? Onde acontecia? O que você fazia? Como tudo terminou?",
    placeholder: "Comece descrevendo onde você estava...",
    minLength: 100,
    maxLength: 3000,
    required: true,
  },
  {
    id: "q11",
    block: 4,
    blockOrder: 3,
    field: "emocao_durante_sonho",
    type: "single",
    text: "Qual foi a emoção mais forte que você sentiu durante o sonho?",
    required: true,
    options: [
      { value: "medo", label: "Medo / terror" },
      { value: "angustia", label: "Angústia / aflição" },
      { value: "tristeza", label: "Tristeza / luto" },
      { value: "confusao", label: "Confusão / estranheza" },
      { value: "alegria", label: "Alegria / paz" },
      { value: "curiosidade", label: "Curiosidade / fascínio" },
      { value: "raiva", label: "Raiva / frustração" },
      { value: "vergonha", label: "Vergonha / culpa" },
      { value: "amor", label: "Amor / conexão" },
    ],
  },
  {
    id: "q12",
    block: 4,
    blockOrder: 4,
    field: "sensacao_ao_acordar",
    type: "single",
    text: "E ao acordar, como você se sentiu?",
    required: true,
    options: [
      { value: "aliviada", label: "Com alívio por ter acordado" },
      {
        value: "triste_terminou",
        label: "Triste, como se algo bom tivesse terminado",
      },
      { value: "confusa", label: "Em confusão, sem entender" },
      {
        value: "inquieta",
        label: "Com inquietação, sem conseguir tirar o sonho da cabeça",
      },
      { value: "em_paz", label: "Em paz, com sensação de mensagem" },
      { value: "real_demais", label: "Sentindo que era “real demais”" },
    ],
  },
  {
    id: "q13",
    block: 4,
    blockOrder: 5,
    field: "personagens",
    type: "multi",
    text: "Quem aparecia no sonho?",
    subtext: "Marque tudo que se aplica",
    required: true,
    minSelections: 1,
    options: [
      { value: "apenas_eu", label: "Apenas eu" },
      { value: "conhecidas_atuais", label: "Pessoas que conheço atualmente" },
      { value: "passado", label: "Pessoas do meu passado" },
      { value: "falecidas", label: "Alguém que já faleceu" },
      { value: "desconhecidas", label: "Pessoas desconhecidas" },
      { value: "figura_religiosa", label: "Figura religiosa ou espiritual" },
      { value: "animais", label: "Animais" },
      { value: "criancas", label: "Crianças" },
      { value: "eu_outra_idade", label: "Eu em outra idade" },
    ],
  },
  {
    id: "q14",
    block: 4,
    blockOrder: 6,
    field: "elementos_simbolicos",
    type: "multi",
    text: "Houve algum elemento ou símbolo que se destacou?",
    subtext: "Marque tudo que aparecer no seu sonho",
    required: true,
    minSelections: 1,
    options: [
      { value: "agua", label: "Água (mar, rio, chuva, inundação)" },
      { value: "fogo", label: "Fogo / queimaduras" },
      { value: "casas", label: "Casas / construções" },
      { value: "estradas", label: "Estradas / caminhos" },
      { value: "veiculos", label: "Veículos (carro, avião, barco)" },
      { value: "animais", label: "Animais" },
      { value: "cores", label: "Cores marcantes" },
      { value: "luz_escuridao", label: "Luz ou escuridão intensas" },
      { value: "voar_cair", label: "Voar ou cair" },
      { value: "ser_perseguida", label: "Perseguição" },
      { value: "dentes_cabelo", label: "Dentes / cabelo / corpo" },
      { value: "objetos_religiosos", label: "Objetos religiosos / sagrados" },
      { value: "nenhum", label: "Nenhum elemento específico" },
    ],
  },

  // BLOCO 5 — Padrões
  {
    id: "q15",
    block: 5,
    blockOrder: 1,
    field: "recorrencia",
    type: "single",
    text: "Esse sonho é recorrente?",
    required: true,
    options: [
      { value: "anos", label: "Sim, sonho com isso há anos" },
      { value: "meses", label: "Sim, sonho com isso há meses" },
      { value: "algumas_vezes", label: "Sim, tive algumas vezes recentemente" },
      { value: "unico", label: "Não, foi único" },
      { value: "nao_sei", label: "Não sei dizer" },
    ],
  },
  {
    id: "q16",
    block: 5,
    blockOrder: 2,
    field: "frequencia_lembranca",
    type: "single",
    text: "Você costuma se lembrar dos seus sonhos?",
    required: true,
    options: [
      { value: "sempre", label: "Sempre, em detalhes" },
      { value: "frequentemente", label: "Frequentemente" },
      { value: "as_vezes", label: "Às vezes" },
      { value: "raramente", label: "Raramente" },
      { value: "quase_nunca", label: "Quase nunca, esse foi uma exceção" },
    ],
  },
  {
    id: "q17",
    block: 5,
    blockOrder: 3,
    field: "tema_recorrente_geral",
    type: "text",
    inputType: "text",
    text: "Existe algum elemento ou tema que aparece com frequência nos seus sonhos em geral?",
    placeholder: "Ex: água, perseguição, cair...",
    required: false,
  },
  {
    id: "q18",
    block: 5,
    blockOrder: 4,
    field: "padrao_recente",
    type: "single",
    text: "Nas últimas semanas, seus sonhos têm sido:",
    required: true,
    options: [
      { value: "mais_intensos", label: "Mais intensos que o normal" },
      { value: "mais_frequentes", label: "Mais frequentes que o normal" },
      { value: "mais_perturbadores", label: "Mais perturbadores que o normal" },
      { value: "normal", label: "Tudo dentro do normal" },
      { value: "mais_raros", label: "Mais raros / não tenho lembrado" },
    ],
  },

  // BLOCO 6 — Sua pergunta
  {
    id: "q19",
    block: 6,
    blockOrder: 1,
    field: "pergunta_principal",
    type: "textarea",
    text: "Se você pudesse fazer UMA pergunta ao seu sonho, qual seria?",
    subtext: "Sua análise vai responder essa pergunta diretamente.",
    placeholder: "Por exemplo: por que esse sonho voltou agora?",
    minLength: 20,
    required: true,
  },
  {
    id: "q20",
    block: 6,
    blockOrder: 2,
    field: "expectativas",
    type: "multi",
    text: "O que você espera descobrir com sua análise Onírica?",
    subtext: "Marque até 3",
    required: true,
    minSelections: 1,
    maxSelections: 3,
    options: [
      { value: "significado_simbolico", label: "O significado simbólico do sonho" },
      { value: "mensagem_espiritual", label: "Uma mensagem espiritual / de Deus" },
      { value: "inconsciente", label: "O que meu inconsciente está processando" },
      { value: "passado", label: "Conexão com algo do meu passado" },
      { value: "orientacao_decisao", label: "Orientação pra uma decisão atual" },
      { value: "aviso_futuro", label: "Aviso sobre o futuro" },
      { value: "compreensao_emocional", label: "Compreensão emocional mais profunda" },
    ],
  },
  {
    id: "q21",
    block: 6,
    blockOrder: 3,
    field: "nivel_crenca",
    type: "scale",
    text: "Em uma escala de 0 a 10, o quanto você acredita que sonhos carregam significado?",
    min: 0,
    max: 10,
    required: true,
  },
  {
    id: "q22",
    block: 6,
    blockOrder: 4,
    field: "informacoes_adicionais",
    type: "textarea",
    text: "Tem algo mais que você queira me contar antes de eu preparar sua análise?",
    placeholder: "Qualquer coisa que ache importante...",
    maxLength: 1000,
    required: false,
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;

// Intro screens content
export const QUIZ_INTRO_CONTENT = {
  title: "Boas-vindas à Onírica.",
  body: [
    "Em alguns minutos, você vai responder algumas perguntas sobre você, seu momento de vida e o sonho que te trouxe até aqui.",
    "Quanto mais sinceridade e detalhe você trouxer, mais profunda será sua análise.",
    "Tudo o que você compartilhar aqui é confidencial e usado apenas pra preparar sua experiência personalizada.",
    "Respira fundo. Vamos começar.",
  ],
  cta: "Quero começar",
};

// The old static block-3 intro now lives in lib/storytelling.ts as the
// "before-dream" interstitial, where it can also mirror the user's answers.

/** Helper: find question by id */
export function findQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}

/** Helper: question at index (0..21) */
export function questionAt(index: number): Question | undefined {
  return QUESTIONS[index];
}
